# Generated by Django 2.2.3 on 2019-08-02 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_goinginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='goinginfo',
            name='student_id',
            field=models.CharField(default='00000', max_length=5),
        ),
        migrations.AddField(
            model_name='goinginfo',
            name='student_pass',
            field=models.CharField(default='00000', max_length=30),
        ),
        migrations.AlterField(
            model_name='goinginfo',
            name='out_day',
            field=models.CharField(default='Friday', max_length=10),
        ),
        migrations.AlterField(
            model_name='goinginfo',
            name='out_hour',
            field=models.IntegerField(default=19),
        ),
        migrations.AlterField(
            model_name='goinginfo',
            name='out_minute',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goinginfo',
            name='return_day',
            field=models.CharField(default='Sunday', max_length=10),
        ),
        migrations.AlterField(
            model_name='goinginfo',
            name='return_hour',
            field=models.IntegerField(default=23),
        ),
        migrations.AlterField(
            model_name='goinginfo',
            name='return_minute',
            field=models.IntegerField(default=0),
        ),
    ]
