# Generated by Django 2.2.4 on 2019-08-17 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190802_1229'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
