# Generated by Django 2.2.4 on 2019-09-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goinginfo',
            name='leave_number',
            field=models.IntegerField(default=0),
        ),
    ]
